incorporated changes from original corrupt branch
chaostoolkit-incubator/chaostoolkit-instana pull request #13
Opened 2019-04-10 12:27 UTC by gtfisher

Signed-off-by: gtfisher <grant@tarrant-fisher.co.uk>

2019-04-10 12:41 UTC, Lawouach requested changes
LbetterTM :)

A few changes requested.
Also you are missing the changelog entry.

2019-04-10 12:41 UTC, Lawouach commented on chaosinstana/api.py
> +        logger.warning("No Instana Host or API Token Secrete were found.")
I would reverse the if/else here:

```
if not (instana_host and instana_api_token):
   raise ActivityFailed("No Instana Host or API Token Secrete were found.")

url = "{}/api/events".format(
            configuration.get("instana_host"))

params = {}
if from_time:
   params["from"] = from_time

if to_time:
   params["to"] = to_time

 r = requests.get(url=url,
                         params=params,
                         headers={
                                 "Authorization": "apiToken {}".format(secrets.get("instana_api_token"))
    }
)

return r.json()
```

2019-04-10 12:41 UTC, Lawouach commented on chaosinstana/probes.py
> +    """
Add these two lines:
```
if not source_time:
   return
```

2019-04-10 12:41 UTC, Lawouach commented on chaosinstana/probes.py
> +    if from_time:
With the change above, you can now remove the if.

2019-04-10 12:41 UTC, Lawouach commented on chaosinstana/probes.py
> +    if to_time:
With the change above, you can now remove the if.

2019-04-12 12:39 UTC, Lawouach commented
Why all these conflicts? :)

2019-04-15 10:46 UTC, gtfisher commented
@Lawouach I think we're ready now to merge barring any final changes?

2019-04-15 11:36 UTC, Lawouach approved these changes
LGTM

2019-04-15 11:36 UTC, Lawouach commented on chaosinstana/api.py
> +    logger.debug("url: {}".format(url))
More a comment than anything else, but those debug statement should usually remain only if they help investigation later on :)

2019-04-15 11:36 UTC, Lawouach commented on chaosinstana/probes.py
> +    logger.debug("from_time {}".format(from_time))
same here :)

2019-04-15 11:37 UTC, Lawouach commented
Thanks for your hardwork!

You can happily merge :)

2019-04-15 12:31 UTC, merged